version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  express-app:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=~.