version: '3'

services:
  web:
    image: nginx
    restart: always
    container_name: "nginx-proxy"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
    ports:
    - "80:80"

  express-app:
    build: ./server
    restart: always
    container_name: "express"
    expose:
      - "3000"
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=requests
      - MONGO_COLLECTION_NAME=events

  postgres:
    image: postgres
    restart: always
    container_name: "pg"
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbinit/postgres:/docker-entrypoint-initdb.d/:ro
      - ./database_files/postgres:/var/lib/postgresql/data

  mongo:
    restart: always
    image: mongo
    restart: always
    container_name: "mongo"
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=requests
    volumes:
      - ./dbinit/mongo:/docker-entrypoint-initdb.d/:ro
      - ./database_files/mongo:/data/db

  mongoadmin:
    restart: always
    image: mongo-express
    restart: always
    container_name: "mongoadmin"
    expose:
      - "8081"
    environment:
      ME_CONFIG_SITE_BASEURL: /mongoadmin

  client-app:
    build: ./client
    restart: always
    container_name: "client"